<?php

use Drupal\ar_drplugin\ArvanCloudPurge;
use Drupal\Core\Routing\RouteMatchInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Implements hook_help().
 */
function ar_drplugin_help($route_name, RouteMatchInterface $route_match) {

    switch ($route_name) {
        case 'help.page.ar_drplugin':

            $text = file_get_contents(__DIR__ . "/README.md");

            if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
                return '<pre>' . $text . '</pre>';
            }

            // Use the Markdown filter to render the README.
            $filter_manager = \Drupal::service('plugin.manager.filter');
            $settings = \Drupal::configFactory()
                ->get('markdown.settings')
                ->getRawData();
            $config = ['settings' => $settings];
            $filter = $filter_manager->createInstance('markdown', $config);
            return $filter->process($text, 'en');
    }

    return NULL;
}
function  ar_drplugin_entity_update(\Drupal\Core\Entity\EntityInterface $entity){
    $settings = \Drupal::configFactory()
        ->get('arvancloud_form.settings')
        ->getRawData();
    ArvanCloudPurge::arPurgeCache($settings["domain"], $settings['api_token']);
}